### ISSUE TITLE
intro videos aren't randomized

### ISSUE THREAD

**Issue by meowthed** [keilmillerjr/randtro-intro#1]
even with the intro settings untouched it still doesn't want to play random video, it just plays whatever attract wants to, console was no help at all.

**Comment by keilmillerjr** [comment]
Can you expand on “it just plays whatever attract wants to”?

**Comment by meowthed** [comment]
It only plays one video despite many videos present in one folder.

**Comment by keilmillerjr** [comment]
If you set video path to a folder path, it will choose a random video within the folder.

**Comment by meowthed** [comment]
it seems that a random video will definitely play in different time intervals, was expecting a random video to play everytime I execute attract.exe.

**Comment by keilmillerjr** [comment]
Good catch! I bet squirrel is generating the same seed each time. I bet if I combine it with time it will resolve this. I’ll work on this after some sleep. Thank you!

**Comment by keilmillerjr** [comment]
helpers-module v1.0.2 contains a fix to resolve the not so random videos issue. Thank you @arnoldsecret for pointing that out to me.

https://github.com/keilmillerjr/helpers-module/releases/tag/v1.0.2
